name: Heroku Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: docker build -t registry.heroku.com/breast-cancer-prediction-app/web .

      - name: Push to Heroku Container Registry
        run: docker push registry.heroku.com/breast-cancer-prediction-app/web

      - name: Release the app
        run: |
          heroku container:release web -a breast-cancer-prediction-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
